server {
  listen 80;
  server_name localhost;

  root /usr/share/nginx/html;
  index index.html;

  location / {
    try_files $uri /index.html;
  }

  location /invoice {
    proxy_pass http://backend:8080;
  }

  location /lineItem {
    proxy_pass http://backend:8080;
  }

  location /invoices {
    proxy_pass http://backend:8080;
  }

  location /lineItems {
    proxy_pass http://backend:8080;
  }
}
